typography_spectrum: 0.43464
color:
  brandColors:
    - '#ffffff'
    - '#958065'
    - '#0a0a0c'
    - '#592a1a'
    - '#ddaa7f'
  brandStrength: 0.5
  lightness: 0.9375
  saturation: 0.75
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.89131
analytics:
  google: null
  facebook: null
  twitter: null
name: dede hourican
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: edtech
purpose: []
