name: dede hourican
favicon: null
layout_spectrum: 0.89131
typography_spectrum: 0.17941408092156053
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#958065'
    - '#0a0a0c'
    - '#592a1a'
    - '#ddaa7f'
  brandStrength: 0.5
  lightness: 0.9375
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
